### ISSUE TITLE
Getting deprecation warning in moment.js

### ISSUE THREAD

**Issue by joelpalmer** [joelpalmer/JSPrescriptions#1]
Need to look in to steps to resolve:

'Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info'

**Comment by cspotcode** [comment]
You can pass a format string to tell moment how to parse your strings.

```
var date = moment('October 10, 1928', 'MMM DD, YYYY');
```

**Comment by joelpalmer** [comment]
Thanks @cspotcode. Working with JS dates has always been challenging and Moment has proven to be very valuable.
